create table if not exists public.scicon_leaderboard (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 15),
  score integer not null check (score >= 0),
  wave integer not null default 1 check (wave >= 1),
  date timestamptz not null default now(),
  wallet_address text,
  donated boolean not null default false,
  proposal_id text,
  proposal_title text,
  proposal_url text,
  proposal_author text,
  created_at timestamptz not null default now(),
  unique (name, score, wave, date)
);

alter table public.scicon_leaderboard
  add column if not exists proposal_id text,
  add column if not exists proposal_title text,
  add column if not exists proposal_url text,
  add column if not exists proposal_author text;

create index if not exists scicon_leaderboard_score_idx
  on public.scicon_leaderboard (score desc, date desc);

create index if not exists scicon_leaderboard_month_idx
  on public.scicon_leaderboard (date desc, score desc);

create index if not exists scicon_leaderboard_wallet_idx
  on public.scicon_leaderboard (wallet_address)
  where wallet_address is not null;

create index if not exists scicon_leaderboard_proposal_idx
  on public.scicon_leaderboard (proposal_id)
  where proposal_id is not null;

alter table public.scicon_leaderboard enable row level security;

create table if not exists public.scicon_monthly_winners (
  id bigint generated by default as identity primary key,
  month_key text not null unique check (month_key ~ '^[0-9]{4}-[0-9]{2}$'),
  month_start timestamptz not null,
  month_end timestamptz not null,
  winner_name text not null check (char_length(winner_name) between 1 and 15),
  score integer not null check (score >= 0),
  wave integer not null default 1 check (wave >= 1),
  score_date timestamptz not null,
  wallet_address text,
  donated boolean not null default false,
  proposal_id text,
  proposal_title text,
  proposal_url text,
  proposal_author text,
  allocation_rsc integer not null default 500 check (allocation_rsc > 0),
  archived_at timestamptz not null default now(),
  notification_sent_at timestamptz
);

alter table public.scicon_monthly_winners
  add column if not exists proposal_id text,
  add column if not exists proposal_title text,
  add column if not exists proposal_url text,
  add column if not exists proposal_author text,
  add column if not exists allocation_rsc integer not null default 500,
  add column if not exists notification_sent_at timestamptz;

create index if not exists scicon_monthly_winners_month_idx
  on public.scicon_monthly_winners (month_key desc);

create index if not exists scicon_monthly_winners_proposal_idx
  on public.scicon_monthly_winners (proposal_id)
  where proposal_id is not null;

alter table public.scicon_monthly_winners enable row level security;
